USE project;

CREATE TABLE messages (
    MessageID INT(10000) NOT NULL AUTO_INCREMENT,
    UIDFROM INT(1000) NOT NULL,
    UIDTO INT(1000) NOT NULL,
    COMMENT VARCHAR (2000) NOT NULL,
    DATE_SENT DATETIME DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (MessageID)
);

INSERT INTO messages (UIDFROM, UIDTO, COMMENT, DATE_SENT)
VALUES (1, 2, 'Thanks for adding me!', DEFAULT );